bitcointranscripts/transcription-review-front-end

- package.json
- src/components/navbar/Navbar.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/utils.ts
This PR is built on top of https://github.com/bitcointranscripts/transcription-review-front-end/pull/3, it should be merged only after https://github.com/bitcointranscripts/transcription-review-front-end/pull/3 has been merged.
Closes https://github.com/adamjonas/transcription-queue/issues/21
> refactor: index page punchlist

- .env
- src/components/editTranscript/EditTranscript.tsx
- src/components/sideBarContentEdit/SelectField.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/sideBarContentEdit/TextField.tsx
- src/components/tables/QueueTable.tsx
- src/hooks/useTranscripts.ts
- src/pages/transcripts/[id].tsx
> Transcript save edit

- src/components/tables/BaseTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
Closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/11
> feat: admin archive

- src/components/modals/SubmitTranscriptModal.tsx
- src/hooks/useTranscripts.ts
- src/pages/transcripts/[id].tsx
Closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/22
> fix: submit promise for edit transcript

- src/components/sideBarContentEdit/SidebarContentEdit.tsx
> fix: reference correct date

- src/api/endpoints.ts
- src/components/tables/BaseTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/hooks/useTranscripts.ts
Closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/28
> feat: archive implementation

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
> fix: reference content and not originalContent field

- src/components/transcript/index.tsx
> fix: include tags when saving edited content

- src/services/api/endpoints.ts
- src/services/api/transcripts/useClaimTranscript.ts
> refactor: new claim endpoint

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/components/tables/types.ts
- src/components/transcript/index.tsx
- src/services/api/endpoints.ts
- src/services/api/reviews/useReview.ts
- src/services/api/reviews/useUserReviews.ts
- types.ts
> Prevent claim while active review

- src/utils.ts
> add new line after transcript_by

- src/components/transcript/index.tsx
- src/pages/reviews/[id].tsx
- src/services/api/endpoints.ts
- src/services/api/reviews/useSubmitReview.ts
> feat: add and implement submitReview service

- src/components/navbar/Navbar.tsx
> rename profile link username to "profile"

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
use proper date instead of created_at,
reorder headers,
add status to past jobs,
relabel status on main queue
> table updates for queue, past and current jobs

- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/components/tables/types.ts
- types.ts
> Add pending reviews to current jobs

- src/components/alerts/SubmitTranscriptAlert.tsx
- src/components/editTranscript/EditTranscript.tsx
- src/components/menus/SubmitTranscriptMenu.tsx
- src/components/sideBarContentEdit/SelectField.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/sideBarContentEdit/selectbox.tsx
- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/components/tables/types.ts
- src/components/transcript/index.tsx
- src/pages/api/github/pr.ts
- src/pages/reviews/[id].tsx
- src/services/api/endpoints.ts
- src/services/api/reviews/useReview.ts
- src/services/api/reviews/useSubmitReview.ts
- src/services/api/reviews/useUserReviews.ts
- src/utils.ts
- types.ts
- refactor getting reviews API call
- prevent users from claiming transcripts if they have an active transcript
- added submitReview service
- added dropdown for admins to make a PR
- added a modal to confirm create PR
> dev to prod

- src/components/tables/CurrentJobsTable.tsx
- types.ts
closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/82
> chore: add pr_url link to reviews table

- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/72
> fix: add data empty text

- package.json
- src/components/home/Queuer.tsx
- src/components/sideBarContentEdit/SelectField.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/sideBarContentEdit/autocomplete.tsx
- src/components/sideBarContentEdit/selectbox.tsx
- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/config/config.json
- src/config/ui-config.ts
- src/pages/api/transcriptMeta.ts
- src/pages/reviews/[id].tsx
- src/services/api/transcripts/useGetMetaData.ts
- types.ts
- yarn.lock
> Typeahead v2 merge

- src/components/alerts/SubmitTranscriptAlert.tsx
- src/components/modals/SubmitTranscriptModal.tsx
> Confirmation modal

- src/components/navbar/Menu.tsx
- src/components/transcript/index.tsx
- src/config/config.json
- src/utils.ts
> Reviewer and profile rename

- src/components/alerts/SubmitTranscriptAlert.tsx
> fix: merge two alerts modal

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/EditableTranscriptsTable.tsx
- src/components/tables/QueueTable.tsx
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/124
> fix: change header of word count

- src/components/home/Steps.tsx
- src/components/tables/EditableTranscriptsTable.tsx
- src/components/tables/QueueTable.tsx
- src/pages/api/transcriptMeta.ts
Fixes: https://github.com/bitcointranscripts/transcription-review-front-end/issues/127
Related: https://github.com/bitcointranscripts/transcription-review-backend/pull/111
> fix: art concerns

- src/pages/api/auth/[...nextauth].ts
- src/services/api/lib.ts
- types.ts
frontend auth setup due to changes in backend auth setup
> feat: auth improvements

- src/components/navbar/Menu.tsx
- src/pages/reviews/[id].tsx
- src/pages/wallet/index.tsx
- src/services/api/endpoints.ts
- src/services/api/wallet/index.ts
- src/services/api/wallet/useTransaction.ts
- src/services/api/wallet/useWallet.ts
- types.ts
- yarn.lock
This pr adds withdrawals of review rewards to the frontend. 
I worked on the The functionality alone, hence the UI is not great
> feat: add lightning invoice payment

- src/components/alerts/WalletAlert.tsx
- src/components/navbar/Menu.tsx
- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/EditableTranscriptsTable.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/components/tables/TransactionsTable.tsx
- src/components/tables/types.ts
- src/config/ui-config.ts
- src/hooks/usePaginatedResult.ts
- src/pages/wallet/index.tsx
- src/services/api/wallet/useTransaction.ts
- types.ts
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/141
> feat: wallet UI

- src/components/GlobalContainer.tsx
- src/components/footer/Footer.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/EditableTranscriptsTable.tsx
- src/components/tables/Pagination.tsx
- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/components/transcript/index.tsx
- src/services/api/endpoints.ts
- src/services/api/reviews/useReview.ts
- src/services/api/reviews/useUserReviews.ts
- src/services/api/transcripts/useTranscripts.ts
- src/utils.ts
- types.ts
https://github.com/bitcointranscripts/transcription-review-front-end/assets/90271995/7b454e6f-dd50-4156-805a-34e6d8b8af4f
1. This PR solves the crashing of staging due to restructuring data
2.  Added a new Pagination component in the queue table and  past jobs table (current job doesn't need one)
3. added a new type for data  restructure
> fix: restructured transcripts data, and added pagination

- src/components/tables/PastJobsTable.tsx
- src/components/tables/QueueTable.tsx
https://github.com/bitcointranscripts/transcription-review-front-end/assets/90271995/b0283356-c091-41cb-8241-81b39a29552c
@Emmanuel-Develops  here
> fix: persit total pages on new requests

- src/components/tables/TransactionsTable.tsx
- src/hooks/usePaginatedResult.ts
This PR aims to unify the pagination on transcripts table (server pagination) and transactions table (client pagination)
> refactor: use pagination component for transaction

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/QueueTable.tsx
- src/utils.ts
> fix: changed the column of time to edit

- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/TitleWithTags.tsx
> fix: padding inline  in table tags

- .eslintrc.json
- src/components/editTranscript/EditTranscript.tsx
- src/components/home/Hero.tsx
- src/components/home/Queuer.tsx
- src/components/home/Steps.tsx
- src/components/home/YoutubePortal.tsx
- src/components/modals/SubmitTranscriptModal.tsx
- src/components/navbar/Menu.tsx
- src/components/navbar/MenuNav.tsx
- src/components/navbar/Navbar.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/sideBarContentEdit/TextField.tsx
- src/components/sideBarContentEdit/autocomplete.tsx
- src/components/sideBarContentEdit/selectbox.tsx
- src/components/tables/BaseTable.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/tables/Pagination.tsx
- src/components/tables/QueueTable.tsx
- src/components/tables/TableItems.tsx
- src/components/tables/types.ts
- src/components/transcript/index.tsx
- src/pages/api/auth/[...nextauth].ts
- src/pages/reviews/[id].tsx
- src/services/api/endpoints.ts
- src/services/api/lib.ts
- src/services/api/reviews/useUserReviews.ts
- src/services/api/transcripts/useTranscripts.ts
- src/utils.ts
Pending on the next PR 
using promise.all for user reviews in current jobs table
> fix: added eslint rule, refactor codebase with specified requirements

- src/components/home/MediaScreen.tsx
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/173
> fix: click to expand on image

- src/components/tables/QueueTable.tsx
- src/components/tables/TitleWithTags.tsx
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/172 and https://github.com/bitcointranscripts/transcription-review-front-end/issues/178
> fix: show all tags

- src/components/sideBarContentEdit/SelectDirectory.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
This PR adds a search functionality while selecting a directory
A Video on How it works below.
https://github.com/bitcointranscripts/transcription-review-front-end/assets/90271995/1904f7c5-bf0c-4058-b479-42cdb171e6ac
> feat: search on directory

- src/components/home/Steps.tsx
- src/components/home/Tutorial.tsx
Closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/185
> fix: move prefer video

- src/components/transcript/index.tsx
- src/pages/api/github/pr.ts
> Same branch on re-submit

- src/pages/reviews/[id].tsx
prevent users from visiting an archived review link
> Fix remove acces to archived reviews

- package.json
- src/components/navbar/AdminMenu.tsx
- src/components/navbar/Menu.tsx
- src/components/tables/AdminTransactionsTable.tsx
- src/config/default.ts
- src/config/ui-config.ts
- src/pages/transactions/index.tsx
- src/services/api/admin/index.ts
- src/services/api/admin/useTransaction.ts
- src/services/api/endpoints.ts
- src/utils.ts
- types.ts
- yarn.lock
> admin transaction page

- src/components/modals/SubmitTranscriptModal.tsx
- src/components/sideBarContentEdit/SelectDirectory.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/components/transcript/index.tsx
- src/pages/api/github/pr.ts
Here is how the resubmit button looks.
This closes #192.
Also closes #186
> fix: resubmit button and PR check logic

- src/components/footer/Footer.tsx
- src/components/home/LandingFooter.tsx
- src/layout/index.tsx
closes #198 and some other stuff
> add umami, twittter card info, adjust landing page footer spacing

- src/components/home/HeroSection.tsx
- src/components/home/LandingPage.tsx
- src/components/home/ReadyToReview.tsx
- src/components/mobileUnsupported/MobileWarningModal.tsx
- src/components/tables/CurrentJobsTable.tsx
- src/hooks/useMobileWarning.ts
- src/services/api/reviews/useUserReviews.ts
> Navigate to queue

- src/components/mobileUnsupported/MobileWarningModal.tsx
- src/layout/index.tsx
> only use analytics on prod

- src/hooks/useNoContainerLimit.ts
- src/layout/index.tsx
This fixes the issue of having double headers
> fix: changed all router.aspath to router.pathname

- src/components/tables/QueueTable.tsx
- src/components/tables/TitleWithTags.tsx
- src/hooks/useNoContainerLimit.ts
- src/layout/index.tsx
- src/utils.ts
- show directory loc
- fix double header on mobile
> minor fixes and improvements

- src/components/home/HeroSection.tsx
- src/components/sideBarContentEdit/SelectField.tsx
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/sideBarContentEdit/autocomplete.tsx
- src/components/sideBarContentEdit/selectbox.tsx
- src/components/tables/TitleWithTags.tsx
- src/styles/globals.css
- src/utils/index.ts
This PR closes #213 and closes #192
> LowerCase tags and incorrect expand on cta in home page

- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/transcript/index.tsx
- src/config/config.json
- src/services/api/transcripts/useUpdateTranscript.ts
- src/utils/transcript.ts
- types.ts
> new-github-implementation-fixes

- src/utils/index.ts
fixes regression on enclosed quotes
initial fix
https://github.com/bitcointranscripts/transcription-review-front-end/commit/ca6bfebd9e3f2ea812aab64d1d25a598ec8f5e05
regression:
https://github.com/bitcointranscripts/transcription-review-front-end/pull/234/commits/a422b4e94b99026edd49250e7494f8d836a134a0
> fix regression on enclosed quotes

- src/components/tables/QueueTable.tsx
- src/components/tables/TitleWithTags.tsx
> Add hyperlink to transcripts & restore missing loc

- src/components/editTranscript/EditTranscript.tsx
- src/components/transcript/index.tsx
This PR closes #254 
Moved the save and submit button to the top of the mark down editor.
Current  Visiblity
TESTED!
> Moved save and submit button for more Visibilty

- src/components/alerts/SubmitTranscriptAlert.tsx
- src/components/modals/ReviewGuidelinesModal.tsx
- src/utils/index.ts
> Update Review Guidelines and pre-submit Modal

- src/components/banner/MaintenanceBanner.tsx
- src/pages/wallet/index.tsx
> create maintenance banner

- .github/workflows/generate-static-data.yml
- package.json
- src/components/sideBarContentEdit/SidebarContentEdit.tsx
- src/components/transcript/index.tsx
- src/pages/api/github/pr.ts
- src/pages/api/github/save.ts
- src/pages/api/transcriptMeta.ts
- src/pages/reviews/[id].tsx
- src/services/api/transcripts/useGetMetadata.ts
- src/services/api/transcripts/useUpdateTranscript.ts
- src/utils/index.ts
- types.ts
- yarn.lock
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/266
This should work for any arbitrary meta data fields we add in the future. Provided they are of the format we currently support: plain string, array of strings and Date. But I do envision us adding boolean meta data some time in the future.
> feat: support arbitrary fields

- src/components/svgs/CopyIcon.tsx
- src/components/tables/AdminTransactionsTable.tsx
- src/components/tables/TableItems.tsx
- src/hooks/useCopyToClipboard.tsx
- src/pages/admin/transactions.tsx
- src/services/api/admin/useTransaction.ts
- types.ts
This PR comes from a Discord discussion on the weird behavior of the admin transaction page.
Also fixes the issue and adds an invoice column to the Table
> Admin transaction Pagination fix

- package.json
- src/components/banner/BossBanner.tsx
- src/components/home/HeroSection.tsx
- src/layout/index.tsx
- src/pages/_app.tsx
- yarn.lock
- Checked-out from main  cherrypick commit in #boss-banner
> Add boss banner on Main

- src/components/home/HeroSection.tsx
- src/layout/index.tsx
Do not merge to main till January 1st 2025
> Queued boss banner removal
